"""add matakuliah table

Revision ID: 91cf8dd85acc
Revises: 7df0b1bdf16e
Create Date: 2025-12-11 17:34:09.423677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cf8dd85acc'
down_revision = '7df0b1bdf16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mk', sa.Text(), nullable=False),
    sa.Column('nama_mk', sa.Text(), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matakuliah')),
    sa.UniqueConstraint('kode_mk', name=op.f('uq_matakuliah_kode_mk'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
